---
title: "Survey II Assignment"
output: html_document
date: "2025-02-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading libraries
```{r}
library(tidyverse)
library(tidyr)
library(haven)
library(readxl)
library(xml2)
library(rvest)
```


## Loading data

### Survey data
```{r}
data_raw <- read_dta("ZA7575.dta")
```

### GDP per capita
Retrieved from Eurostat for the year 2019 (https://ec.europa.eu/eurostat/databrowser/view/tipsna40/default/table?lang=en).
```{r}
gdp_data <- read_xlsx("gdp_pc_2019.xlsx", sheet = 3, range = "A11:B39", col_names = c("country", "gdp_pc"))
head(gdp_data)
```
### Same sex unions

Retrieved from Wikipedia.
```{r}
link <- "https://en.wikipedia.org/wiki/Recognition_of_same-sex_unions_in_Europe"
html_website <- link |> read_html()
all_tables <- html_website|> html_table()
marriage_data <- all_tables[[4]]
marriage_data <- marriage_data |> select(Status, Country)

# cleaning the status column
marriage_data$Status <- sub("\\s*\\(.*|\\s*-.*", "", marriage_data$Status)
unique(marriage_data$Status)

# cleaning the country column
marriage_data <- marriage_data |> 
  mutate(Country = str_replace_all(Country, c("\\*" = "", "†" = "", "\\[.*?\\]" = ""))) |> 
  mutate(Country = trimws(Country))
unique(marriage_data$Country)

# getting rid of the total and subtotal rows
marriage_data <- marriage_data |> 
  filter(!Status %in% c("Total", "Subtotal"))
```
This variable could be recoded as either ordinal, categorical (both factor) or logical.
### Degree of urbanisation


## Data cleaning

